# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_asPhoenixLive', [dirname(__file__)])
        except ImportError:
            import _asPhoenixLive
            return _asPhoenixLive
        if fp is not None:
            try:
                _mod = imp.load_module('_asPhoenixLive', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _asPhoenixLive = swig_import_helper()
    del swig_import_helper
else:
    import _asPhoenixLive
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def phxlive(*args):
  return _asPhoenixLive.phxlive(*args)
phxlive = _asPhoenixLive.phxlive

def buffer_ready_count():
  return _asPhoenixLive.buffer_ready_count()
buffer_ready_count = _asPhoenixLive.buffer_ready_count

def buffer_overflow():
  return _asPhoenixLive.buffer_overflow()
buffer_overflow = _asPhoenixLive.buffer_overflow
class tPhxLive(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, tPhxLive, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, tPhxLive, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nBufferReadyCount"] = _asPhoenixLive.tPhxLive_nBufferReadyCount_set
    __swig_getmethods__["nBufferReadyCount"] = _asPhoenixLive.tPhxLive_nBufferReadyCount_get
    if _newclass:nBufferReadyCount = _swig_property(_asPhoenixLive.tPhxLive_nBufferReadyCount_get, _asPhoenixLive.tPhxLive_nBufferReadyCount_set)
    __swig_setmethods__["fFifoOverFlow"] = _asPhoenixLive.tPhxLive_fFifoOverFlow_set
    __swig_getmethods__["fFifoOverFlow"] = _asPhoenixLive.tPhxLive_fFifoOverFlow_get
    if _newclass:fFifoOverFlow = _swig_property(_asPhoenixLive.tPhxLive_fFifoOverFlow_get, _asPhoenixLive.tPhxLive_fFifoOverFlow_set)
    def __init__(self): 
        this = _asPhoenixLive.new_tPhxLive()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _asPhoenixLive.delete_tPhxLive
    __del__ = lambda self : None;
tPhxLive_swigregister = _asPhoenixLive.tPhxLive_swigregister
tPhxLive_swigregister(tPhxLive)



def py_camera_live(*args):
  return _asPhoenixLive.py_camera_live(*args)
py_camera_live = _asPhoenixLive.py_camera_live

