# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_D4000', [dirname(__file__)])
        except ImportError:
            import _D4000
            return _D4000
        if fp is not None:
            try:
                _mod = imp.load_module('_D4000', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _D4000 = swig_import_helper()
    del swig_import_helper
else:
    import _D4000
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def py_illuminate_vector(*args):
  return _D4000.py_illuminate_vector(*args)
py_illuminate_vector = _D4000.py_illuminate_vector

def py_illuminate_spot_find(*args):
  return _D4000.py_illuminate_spot_find(*args)
py_illuminate_spot_find = _D4000.py_illuminate_spot_find

def py_illuminate_point(*args):
  return _D4000.py_illuminate_point(*args)
py_illuminate_point = _D4000.py_illuminate_point

def py_illum_mask_radius(*args):
  return _D4000.py_illum_mask_radius(*args)
py_illum_mask_radius = _D4000.py_illum_mask_radius

def py_clear_framebuffer():
  return _D4000.py_clear_framebuffer()
py_clear_framebuffer = _D4000.py_clear_framebuffer

def py_clear_memory():
  return _D4000.py_clear_memory()
py_clear_memory = _D4000.py_clear_memory

def py_illuminate_expose():
  return _D4000.py_illuminate_expose()
py_illuminate_expose = _D4000.py_illuminate_expose

def py_clear_mask(*args):
  return _D4000.py_clear_mask(*args)
py_clear_mask = _D4000.py_clear_mask

def py_illuminate_init(*args):
  return _D4000.py_illuminate_init(*args)
py_illuminate_init = _D4000.py_illuminate_init

def py_illuminate_enable():
  return _D4000.py_illuminate_enable()
py_illuminate_enable = _D4000.py_illuminate_enable

def py_illuminate_disable():
  return _D4000.py_illuminate_disable()
py_illuminate_disable = _D4000.py_illuminate_disable

def py_light_all():
  return _D4000.py_light_all()
py_light_all = _D4000.py_light_all

def py_illuminate_float():
  return _D4000.py_illuminate_float()
py_illuminate_float = _D4000.py_illuminate_float

def py_illuminate_alignment_load(*args):
  return _D4000.py_illuminate_alignment_load(*args)
py_illuminate_alignment_load = _D4000.py_illuminate_alignment_load

def py_illuminate_alignment_load_identity():
  return _D4000.py_illuminate_alignment_load_identity()
py_illuminate_alignment_load_identity = _D4000.py_illuminate_alignment_load_identity


