# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_polProcDMD', [dirname(__file__)])
        except ImportError:
            import _polProcDMD
            return _polProcDMD
        if fp is not None:
            try:
                _mod = imp.load_module('_polProcDMD', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _polProcDMD = swig_import_helper()
    del swig_import_helper
else:
    import _polProcDMD
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def py_send_DMD_register_image(*args):
  return _polProcDMD.py_send_DMD_register_image(*args)
py_send_DMD_register_image = _polProcDMD.py_send_DMD_register_image

def py_get_X_offset():
  return _polProcDMD.py_get_X_offset()
py_get_X_offset = _polProcDMD.py_get_X_offset

def py_get_Y_offset():
  return _polProcDMD.py_get_Y_offset()
py_get_Y_offset = _polProcDMD.py_get_Y_offset

def py_start_network_server():
  return _polProcDMD.py_start_network_server()
py_start_network_server = _polProcDMD.py_start_network_server

def py_stop_network_server():
  return _polProcDMD.py_stop_network_server()
py_stop_network_server = _polProcDMD.py_stop_network_server

def py_force_network_shutdown():
  return _polProcDMD.py_force_network_shutdown()
py_force_network_shutdown = _polProcDMD.py_force_network_shutdown


